# Generated by Django 5.0.6 on 2024-06-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_token_token_alter_token_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sugar', models.IntegerField()),
                ('chocolate', models.IntegerField()),
                ('coffee', models.IntegerField()),
                ('flour', models.IntegerField()),
                ('vertical', models.BinaryField(max_length=10)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
