# Generated by Django 5.0.6 on 2024-06-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
