# Generated by Django 5.0.6 on 2024-07-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sales',
            field=models.JSONField(default=dict),
        ),
    ]
