# Generated by Django 5.0.6 on 2024-07-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_category_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sales',
        ),
    ]
