# Generated by Django 5.0.6 on 2024-07-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_category_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sales',
        ),
    ]
